# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 03:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('content', models.CharField(max_length=200, verbose_name='内容')),
                ('created', models.DateTimeField(auto_now=True, verbose_name='创建时间')),
            ],
        ),
    ]
