# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 04:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidemo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=200, verbose_name='描述')),
                ('start', models.DateTimeField()),
                ('finish', models.DateTimeField()),
                ('name', models.CharField(max_length=30, verbose_name='名字')),
                ('room_number', models.IntegerField()),
                ('date', models.DateField()),
            ],
        ),
    ]
