# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-12 14:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apidemo', '0002_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='additional_param',
            field=models.CharField(default='simple', max_length=20, verbose_name='额外参数'),
        ),
    ]
